version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - aws --version
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login -u shaharukh789 -p PC11**st
      - echo "Building Docker image..."
      - docker build -t shaharukh789/aiweb .
  build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push shaharukh789/aiweb
  post_build:
    commands:
      - echo "Cleaning up..."
      - docker logout

artifacts:
  files:
    - '**/*'
